version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - service_network

networks:
  service_network:
    external: true
